# Generated by Django 5.2.8 on 2025-11-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ugcitem',
            name='cached_hot',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ugcitem',
            name='cached_top',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ugcitem',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
